workflow:
    name: Fetch IP

stages:
  - fetch

variables:
  POSTGRES_DB: iptracker
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  - postgres:13
  
build-job:
  stage: fetch
  image: python:3.9
  before_script:
      - pip install -r requirements.txt
  script:
    - cd app
    - chmod +x log_ip.sh
    - apt-get update && apt-get install -y jq
    - python api.py
    - ./log_ip.sh
    - cat ip_log.txt
  artifacts:
      paths:
        - app/ip.json
        - app/fetched_details.txt
        - app/ip_log.txt  
